### ISSUE TITLE
"error: something happened"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/preferred_providers#36]
![image](https://user-images.githubusercontent.com/5836855/234778762-3a38b3ec-cd2c-46d5-9507-8e8172d04fa4.png)

I just tried it with Android and it fails.

**Comment by skjnldsv** [comment]
What is the problem exactly?

**Comment by nickvergessen** [comment]
There is a "400 Bad Request" being logged in the access.log on nextcloud.com basically for all of the requests. Just saw it and passed it on. I have no further info

**Comment by tobiasKaminsky** [comment]
Just try to create an account.
It directly says "error: something happened"…

I cannot provide any more info… :S
